### ISSUE TITLE
Deep Linking with Intents in Android?

### ISSUE THREAD

**Issue by mdridley** [lampaa/org.apache.cordova.startapp#13]
I am trying to deep link with this using an argument... not sure why it is not working:
```js
navigator.startApp.start('com.facebook.katana', [{"index":"https://www.facebook.com/GitHub"}],function(message) {
	console.log('Facebook app launched');
}, 
function(error) {
	//App Not available, open in browser
	console.log(error);
	$window.open(url, '_blank', 'location=no')
});
```

App launches... but I am getting errors (and it only opens to default page, not requested):
```
D/CordovaLog( 7445): file:///android_asset/www/cordova.js: Line 1059 : processMessage failed: Error: TypeError: Object [object Array] has no method 'apply'
D/CordovaLog( 7445): file:///android_asset/www/cordova.js: Line 1060 : processMessage failed: Stack: TypeError: Object [object Array] has no method 'apply'
D/CordovaLog( 7445):     at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:293:54)
D/CordovaLog( 7445):     at processMessage (file:///android_asset/www/cordova.js:1054:21)
D/CordovaLog( 7445):     at androidExec.processMessages (file:///android_asset/www/cordova.js:1091:13)
```

**Comment by lampaa** [comment]
Hi, @mdridley. 
See documentation...:
First parameter is array or string. second and third as success and error callbacks.

See my variant
```js
// check for facebook app is installed
var page = "https://www.facebook.com/GitHub";

navigator.startApp.check("com.facebook.katana", function(message) { /* success */
    navigator.startApp.start([["action", "ACTION_VIEW"], ["fb://facewebmodal/f?href=" + page], function(a) { 
        console.log(a); // => OK
    }, 
    function(error) { /* error */
        navigator.startApp.start([["action", "VIEW"], [page], function() {}, function () {});
    });
}, 
function(error) { /* error */
    navigator.startApp.start([["action", "VIEW"], [page], function() {}, function () {});
});
```

**Comment by mdridley** [comment]
I was not sure where to put the second bracket, so I did:

$window.navigator.startApp.check(
		    schemes[siteType][devicePlatform],
		    function() {  // App Installed, Open It
		    	if (devicePlatform = 'Android') {
		    		$window.navigator.startApp.start([["action", "ACTION_VIEW"], ['fb://facewebmodal/f?href=' + url]], function(a) { 
				        console.log(a); // => OK
				    }, 
				    function(error) { /* error */
				        // open in browser if there is an error
				        console.log(error);
				        $window.open(url, '_blank', false);
				    })
		    	} else {
		        	$window.open(iosFullLink, '_system', false);
		    	}
		    },
		    function() {  // Open Web Page
				$window.open(url, '_blank', false);
		    }
		);

But getting this new error now:
intent: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.ACTION_VIEW dat=fb://facewebmodal/f?href=http://www.facebook.com/GitHub/

**Comment by lampaa** [comment]
@mdridley oh, sorry!
Replase ```ACTION_VIEW``` to ```VIEW```

**Comment by mdridley** [comment]
That worked perfectly! Thank you!
